#+title: Claude lab

This repository contains the app code to run a claude-light server and to interact with it through Python.

It is a WIP.

* Setup
** Register the MAC address

At CMU it is necessary to do this so you can get an IP address.

** Setup the Raspberry Pi

This is mostly a one time setup on a new pi.

I recommend running all the updates. You may want to run raspi-config to update first.

#+BEGIN_SRC sh
sudo apt update && apt full-upgrade && apt clean
#+END_SRC

Maybe this should be done weekly? You can find a script for this at [[./update-pi.sh]].

You have to enable the I2C interface in raspi-config

#+BEGIN_SRC sh
sudo raspi-config
#+END_SRC

go to interface options, then to I2C to enable it. I don't recall if a reboot is necessary.

** Setup and activate a virtual environment for Python

I suggest you run this in ~/

#+BEGIN_SRC sh
python -m venv .venv
#+END_SRC

I also recommend add this line to .bashrc so it loads when you login.

#+BEGIN_SRC sh
source ~/.venv/bin/activate
#+END_SRC

If not, you have to manually run this.

** Install claude

The package is only available on GitHUB. Install it like this.

#+BEGIN_SRC sh
pip install git+git://github.com/jkitchin/claude-light
#+END_SRC

Alternatively

#+BEGIN_SRC sh
git clone git@github.com:jkitchin/claude-light.git
pip install -e claude
#+END_SRC


I think this will install all the dependencies and it should also install a cli called ~claude~ that will start the app. Normally you would only run this on the Raspberry Pi.

You also have to set  up /etc/rc.local to automatically start the server when it boots up. To achieve this, add something like this before the ~exit 0~ line.:

sudo -u jkitchin claude &

It is a little tricky to kill the server. So far I use:

#+BEGIN_SRC sh
pkill claude
#+END_SRC


** Access the server

This url is only available on CMU campus or with the CMU VPN:

http://claude2.cheme.local.cmu.edu:5000/?R=0.4&G=0.5&B=0.9

The R, G and B parameters can be between 0-1.
